// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABGrYl6J_kifxaYL6R2Kw08qmnLNnxId4',
    appId: '1:301810493701:web:a072739c2c61eafefd6f6c',
    messagingSenderId: '301810493701',
    projectId: 'my-project-spendo',
    authDomain: 'my-project-spendo.firebaseapp.com',
    storageBucket: 'my-project-spendo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyRdw8DNQv0oeIqtmziwYQh4GHbtsSepk',
    appId: '1:301810493701:android:a62646c848161c1efd6f6c',
    messagingSenderId: '301810493701',
    projectId: 'my-project-spendo',
    storageBucket: 'my-project-spendo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfjbY1lprDW7oKG6xQEJXqvXy4quPl33Y',
    appId: '1:301810493701:ios:be6edbb276ab791bfd6f6c',
    messagingSenderId: '301810493701',
    projectId: 'my-project-spendo',
    storageBucket: 'my-project-spendo.firebasestorage.app',
    iosBundleId: 'com.example.spendo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABGrYl6J_kifxaYL6R2Kw08qmnLNnxId4',
    appId: '1:301810493701:web:7465c6b7e9782721fd6f6c',
    messagingSenderId: '301810493701',
    projectId: 'my-project-spendo',
    authDomain: 'my-project-spendo.firebaseapp.com',
    storageBucket: 'my-project-spendo.firebasestorage.app',
  );
}
